#ifndef EP2_PACKAGE_TYPE_H
#define EP2_PACKAGE_TYPE_H

typedef enum {
    CONNECT_PACKAGE,
    RECONNECT_PACKAGE,
    LOGIN_PACKAGE,
    LOGIN_ACK_PACKAGE,
    LOGOUT_PACKAGE,
    CREATE_USER_PACKAGE,
    CREATE_USER_ACK_PACKAGE,
    CHANGE_PASSWORD_PACKAGE,
    CHANGE_PASSWORD_ACK_PACKAGE,
    REQUEST_ALL_CONNECTED_USERS_PACKAGE,
    RESPONSE_ALL_CONNECTED_USERS_PACKAGE,
    REQUEST_CLASSIFICATIONS_PACKAGE,
    RESPONSE_CLASSIFICATIONS_PACKAGE,
    INVITE_OPPONENT_PACKAGE,
    INVITE_OPPONENT_ACK_PACKAGE,
    START_MATCH_PACKAGE,
    SEND_MOVE_PACKAGE,
    END_MATCH_PACKAGE,
    PINGREQ_PACKAGE,
    PINGBACK_PACKAGE,
} package_t;

#endif //EP2_PACKAGE_TYPE_H
